spring.application.name=projectmanagement
# Application Configuration

# Application Configuration
server.port=${PORT:8082}
server.servlet.context-path=${CONTEXT_PATH:/api}

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/jiraxxxx?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Security Configuration
jwt.secret=${JWT_SECRET:dcfvgbhj345376387yeu8jh3v4cre78gd22cdvo2y7643s54durftd65fi7t6yu4es75dr6f8t7gyh8ud5f7t6yhux6drfitygyuyhu7hu}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.com.jiraclone=DEBUG

# CORS Configuration
spring.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600

# OpenAI API Configuration
openai.api.url=${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
openai.api.key=${OPENAI_API_KEY:}